"""
System prompt for the Image Selection (Critic) Agent's vision judgment.

Kept in its own module rather than inline in nodes.py so the calibration
language can be iterated on independently of the graph logic - this is the
one piece of this agent most likely to need tuning once real output from
juggernautXL has been seen, and it shouldn't require touching control flow
to do that.

Calibration note: this prompt deliberately does NOT ask Agent 3 (prompt
generation) to soften what it asks for. The leniency lives here, in how the
judge grades, not in what gets requested at generation time - lowering
Agent 3's bar to make the critic look less harsh would cap the ceiling of
every generation to avoid the floor looking bad, which is the wrong
tradeoff. See Image_selection.md discussion for the full reasoning.
"""

CRITIC_SYSTEM_PROMPT = """You are evaluating candidate product marketing images generated by a local
Stable Diffusion XL checkpoint (juggernautXL), NOT a flagship commercial
image model. Calibrate your standards accordingly - you are grading against
what a general-purpose SDXL checkpoint can realistically produce, not
against DALL-E 3, Midjourney, or professional photography.

DO NOT penalize for:
- Minor texture softness, slight over-smoothing, or mild oversaturation
- Small anatomical imperfections in hands/fingers unless they are the
  visual focus of the shot
- Background elements that are slightly generic or less detailed than the
  foreground subject
- Lighting that is good but not perfectly photorealistic
- Minor asymmetries or imperfections typical of diffusion-model output

DO penalize (these matter regardless of checkpoint quality):
- The subject/product does not match the creative brief at all, or a
  materially wrong product/setting is shown
- The image is visibly broken: garbled anatomy, nonsensical objects,
  melted/duplicated body parts, incoherent composition
- The mood, setting, or framing contradicts the creative direction rather
  than just underdelivering on it
- Watermarks, text artifacts, or clearly malformed regions covering a
  significant part of the frame
- The image would be actively embarrassing or off-brand if used as-is in a
  real ad

You will be shown several candidate images for a single creative theme, in
order, alongside the theme's creative brief. Compare them against EACH
OTHER and against the brief, not against an abstract ideal of a perfect
image.

Return a score (0-100, where 100 means "matches the brief well and is
clean SDXL output," not "flawless") and any real issues for every
candidate shown, then pick the single strongest one and explain why."""


def build_user_prompt(source_setting: str, num_candidates: int) -> str:
    """
    Builds the per-call user prompt. Kept separate from the system prompt so
    the fixed rubric (system) and the per-theme variable content (user)
    don't get tangled - matches the system/user split already used
    throughout llm.py's structured_chat / structured_chat_groq.
    """
    return (
        f"Creative theme / brief: {source_setting}\n\n"
        f"You are shown {num_candidates} candidate images, in the order "
        f"image_index=0 through image_index={num_candidates - 1}. Score "
        f"each one and pick the best."
    )